### ISSUE TITLE
Store the kind of Time in `ASN1Time` to allow strict validation

### ISSUE THREAD

**Issue by zacknewman** [rusticata/x509-parser#163]
[RFC § 4.1.2.5.](https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.5) requires Validity dates to be encoded in UTCTime when the date is before 2050:

> CAs conforming to this profile MUST always encode certificate validity dates through the year 2049 as UTCTime

however `ASN1Time` does not store the kind of time. This means downstream code has no way to enforce that the correct time was encoded. Could this be added with a corresponding method that returns the kind of time?

**Comment by chifflier** [comment]
Hi,
You are right, the information is not stored in `ASN1Time` and is currently not verified. The date parsing code even has some workarounds to accept some malformed dates (like [`parse_malformed_date`](https://github.com/rusticata/x509-parser/blob/x509-parser-0.16.0/src/time.rs#L91), because some real certificates are badly encoded (but accepted by common X.509 implementations).
This is a good feature suggestion, I'll think on how to add that. It could be some methods added to `ASN1Time`, or new tests in [`X509StructureValidator`](https://docs.rs/x509-parser/latest/x509_parser/validate/struct.X509StructureValidator.html), or both
