### ISSUE TITLE
Best way to parse X509 certificates chain?

### ISSUE THREAD

**Issue by leplatrem** [rusticata/x509-parser#75]
From what I can tell, the parser only parses the last certificate block in the chain (PEM).

In my use case I would like to be able to access each certificate of the sequence.
*(In order to verify that the root certificate has a known fingerprint, and that each subsequent certificate signature can be verified with the public key of its ancestor).*

Is it already possible?
Would you be interested in expanding your API for that? With some guidance, I would be happy to contribute it ;) 

Thanks for your time & feedback!

**Comment by chifflier** [comment]
Hi,
Indeed, a PEM bundle can contain several certificates, and currently `Pem::read` only returns one (I think the first in order of appearance).
My first thought would be to add an iterator over certificates in the `Pem`. Since `Pem::read` returns the offset after reading, this should not be too difficult.
The only annoying thing is the return type: there are plenty of reasons to fail (invalid header, etc.), so the iterator should be fallible, and the Rust iterator API is not good for that :/ We can return a `Option<Result<Pem>, PEMError>`, though

**Comment by chifflier** [comment]
Hi,
Thank you for the idea and the proposed contribution.
As I'd like to release a new version soon, I added the feature: `Pem::iter_from_buffer` returns an iterator over `Result<Pem, PEMError>` objects.

**Comment by leplatrem** [comment]
Awesome! Thanks, that was really easy to use :)
